pca_n_comps = 14
disp_scores = True
save_mode = 'DAG'
dataset = 'ods'

q_canc = """
SELECT 
    PRCHS_NR, 
    PRCHS_DCMNT_ITEM,
    VEND_NR,
    DSTRBTN_CHNL,
    PRCHS_DCMNT_TYP,
    LTRIM(CAST(HIERCY_NODE_2 AS STRING), '0') HIERCY_NODE_2,
    CARTD1.VOLUNIT, 
    CARTD1.VOLUNIT_ITEM,
    QTY,
    GRS_VAL_SLS_CRNCY,
    VLR_MIN_ORD,
    CARTD1.GRS_WGT, 
    LT_TRAN,
    SCHDL_PLAN_DVSN_DCMNT_DT, 
    PRCHS_DCMNT_DT,
    DATE_DIFF(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as PROMISED_LEAD_TIME,
    DATE_DIFF(CAST(CANC_DT AS DATE), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as DAYS_OPEN,
FROM

WHERE
  DIM_MTRL.MTRL_TYP = 'ZREV' 
  AND PRCHS_STUS_ITEM >= '90'
  AND DSTRBTN_CHNL <> 'Z01'
  AND PRCHS_DCMNT_DT >= DATE_ADD(CURRENT_DATE(), INTERVAL -365 DAY)
  AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL
  AND CANC_DT IS NOT NULL
  AND LT_TRAN IS NOT NULL
  AND VLR_MIN_ORD IS NOT NULL
  AND DSTRBTN_CHNL IS NOT NULL
  AND CARTD1.VOLUNIT IS NOT NULL
  AND HIERCY_NODE_2 IS NOT NULL
"""

q_late = """
SELECT 
    PRCHS_NR, 
    PRCHS_DCMNT_ITEM,
    VEND_NR,
    DSTRBTN_CHNL,
    PRCHS_DCMNT_TYP,
    LTRIM(CAST(HIERCY_NODE_2 AS STRING), '0') HIERCY_NODE_2,
    CARTD1.VOLUNIT, 
    CARTD1.VOLUNIT_ITEM,
    QTY,
    GRS_VAL_SLS_CRNCY,
    VLR_MIN_ORD,
    CARTD1.GRS_WGT, 
    LT_TRAN,
    SCHDL_PLAN_DVSN_DCMNT_DT, 
    PRCHS_DCMNT_DT,
    DATE_DIFF(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as PROMISED_LEAD_TIME,
    DATE_DIFF(CAST(PSTNG_DT AS DATE), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as DAYS_OPEN,
FROM

WHERE
  DIM_MTRL.MTRL_TYP = 'ZREV' 
  AND PRCHS_STUS_ITEM IN ('40', '60')
  AND PRCHS_DCMNT_DT >= DATE_ADD(CURRENT_DATE(), INTERVAL -365 DAY)
  AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL
  AND LT_TRAN IS NOT NULL
  AND VLR_MIN_ORD IS NOT NULL
  AND DSTRBTN_CHNL IS NOT NULL
  AND DSTRBTN_CHNL <> 'Z01'
  AND PSTNG_DT>SCHDL_PLAN_DVSN_DCMNT_DT
  AND CARTD1.VOLUNIT IS NOT NULL
  AND HIERCY_NODE_2 IS NOT NULL
"""

q_on_time = q_late = """
SELECT 
    PRCHS_NR, 
    PRCHS_DCMNT_ITEM,
    VEND_NR,
    DSTRBTN_CHNL,
    PRCHS_DCMNT_TYP,
    LTRIM(CAST(HIERCY_NODE_2 AS STRING), '0') HIERCY_NODE_2,
    CARTD1.VOLUNIT, 
    CARTD1.VOLUNIT_ITEM,
    QTY,
    GRS_VAL_SLS_CRNCY,
    VLR_MIN_ORD,
    CARTD1.GRS_WGT, 
    LT_TRAN,
    SCHDL_PLAN_DVSN_DCMNT_DT, 
    PRCHS_DCMNT_DT,
    DATE_DIFF(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as PROMISED_LEAD_TIME,
    DATE_DIFF(CAST(PSTNG_DT AS DATE), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as DAYS_OPEN,
FROM

WHERE
  DIM_MTRL.MTRL_TYP = 'ZREV' 
  AND PRCHS_STUS_ITEM IN ('40', '60')
  AND PRCHS_DCMNT_DT >= DATE_ADD(CURRENT_DATE(), INTERVAL -365 DAY)
  AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL
  AND LT_TRAN IS NOT NULL
  AND VLR_MIN_ORD IS NOT NULL
  AND DSTRBTN_CHNL IS NOT NULL
  AND DSTRBTN_CHNL <> 'Z01'
  AND PSTNG_DT<=SCHDL_PLAN_DVSN_DCMNT_DT
  AND CARTD1.VOLUNIT IS NOT NULL
  AND HIERCY_NODE_2 IS NOT NULL
"""

q_open = """
SELECT 
    PRCHS_NR, 
    PRCHS_DCMNT_ITEM,
    VEND_NR,
    DSTRBTN_CHNL,
    PRCHS_DCMNT_TYP,
    LTRIM(CAST(HIERCY_NODE_2 AS STRING), '0') HIERCY_NODE_2,
    CARTD1.VOLUNIT, 
    CARTD1.VOLUNIT_ITEM,
    QTY,
    GRS_VAL_SLS_CRNCY,
    VLR_MIN_ORD,
    CARTD1.GRS_WGT, 
    LT_TRAN,
    SCHDL_PLAN_DVSN_DCMNT_DT, 
    PRCHS_DCMNT_DT,
    DATE_DIFF(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as PROMISED_LEAD_TIME,
    DATE_DIFF(CURRENT_DATE(), CAST(PRCHS_DCMNT_DT AS DATE), DAY) as DAYS_OPEN,
FROM

WHERE
  DIM_MTRL.MTRL_TYP = 'ZREV' 
  AND PRCHS_STUS_ITEM NOT IN ('40', '60', '90', '91')
  AND PRCHS_DCMNT_DT >= DATE_ADD(CURRENT_DATE(), INTERVAL -365 DAY)
  AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL
  AND LT_TRAN IS NOT NULL
  AND VLR_MIN_ORD IS NOT NULL
  AND DSTRBTN_CHNL IS NOT NULL
  AND DSTRBTN_CHNL <> 'Z01'
  AND CARTD1.VOLUNIT IS NOT NULL
  AND HIERCY_NODE_2 IS NOT NULL
"""

q_global_deliv = """
SELECT
    {cat_col},
    CASE 
        WHEN TOT_ORD_PRCHS_QTY_LAST_YR_HIERCY_NODE_2 = 0 THEN 0
        ELSE TOT_ON_TIME_ORD_PRCHS_QTY_LAST_YR_HIERCY_NODE_2 / TOT_ORD_PRCHS_QTY_LAST_YR_HIERCY_NODE_2 
    END {cat_col}_ON_TIME_YR_PCT,
    CASE 
        WHEN TOT_ORD_PRCHS_QTY_LAST_MTH_HIERCY_NODE_2 = 0 THEN 0
        ELSE TOT_ON_TIME_ORD_PRCHS_QTY_LAST_MTH_HIERCY_NODE_2 / TOT_ORD_PRCHS_QTY_LAST_MTH_HIERCY_NODE_2 
    END {cat_col}_ON_TIME_LAST_MTH_PCT,
    CASE 
        WHEN TOT_ORD_PRCHS_QTY_LAST_TWO_MTH_HIERCY_NODE_2 = 0 THEN 0
        ELSE TOT_ON_TIME_ORD_PRCHS_QTY_LAST_TWO_MTH_HIERCY_NODE_2 / TOT_ORD_PRCHS_QTY_LAST_TWO_MTH_HIERCY_NODE_2 
    END {cat_col}_ON_TIME_LAST_TWO_MTH_PCT,
    CASE 
        WHEN TOT_ORD_PRCHS_QTY_LAST_THREE_MTH_HIERCY_NODE_2 = 0 THEN 0
        ELSE TOT_ON_TIME_ORD_PRCHS_QTY_LAST_THREE_MTH_HIERCY_NODE_2 / TOT_ORD_PRCHS_QTY_LAST_THREE_MTH_HIERCY_NODE_2 
    END {cat_col}_ON_TIME_LAST_THREE_MTH_PCT,
FROM (
	SELECT
	  LTRIM(CAST(TOT_YR.{cat_col} AS STRING), '0') {cat_col},
	  IFNULL(TOT_YR.TOT_ORD_PRCHS_QTY_LAST_YR, 0) TOT_ORD_PRCHS_QTY_LAST_YR_HIERCY_NODE_2,
	  IFNULL(ON_TIME_YR.TOT_ON_TIME_ORD_PRCHS_QTY_LAST_YR, 0) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_YR_HIERCY_NODE_2,
	  IFNULL(TOT_LAST_MTH.TOT_ORD_PRCHS_QTY_LAST_MTH, 0) TOT_ORD_PRCHS_QTY_LAST_MTH_HIERCY_NODE_2,
	  IFNULL(ON_TIME_LAST_MTH.TOT_ON_TIME_ORD_PRCHS_QTY_LAST_MTH, 0) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_MTH_HIERCY_NODE_2,
	  IFNULL(TOT_LAST_TWO_MTH.TOT_ORD_PRCHS_QTY_LAST_TWO_MTH, 0) TOT_ORD_PRCHS_QTY_LAST_TWO_MTH_HIERCY_NODE_2,
	  IFNULL(ON_TIME_LAST_TWO_MTH.TOT_ON_TIME_ORD_PRCHS_QTY_LAST_TWO_MTH, 0) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_TWO_MTH_HIERCY_NODE_2,
	  IFNULL(TOT_LAST_THREE_MTH.TOT_ORD_PRCHS_QTY_LAST_THREE_MTH, 0) TOT_ORD_PRCHS_QTY_LAST_THREE_MTH_HIERCY_NODE_2,
	  IFNULL(ON_TIME_LAST_THREE_MTH.TOT_ON_TIME_ORD_PRCHS_QTY_LAST_THREE_MTH, 0) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_THREE_MTH_HIERCY_NODE_2,
	FROM (
		SELECT DISTINCT -- 365 ALL ORDERS
			CARTD1.{cat_col}, 
			count(PRCHS_DCMNT_ITEM) TOT_ORD_PRCHS_QTY_LAST_YR
		FROM 
        
		WHERE 
			PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -365 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -1 DAY)
			AND DIM_MTRL.MTRL_TYP = 'ZREV' 
			AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
			AND LT_TRAN IS NOT NULL 
			AND VLR_MIN_ORD IS NOT NULL
			AND CARTD1.{cat_col} IS NOT NULL 
			AND CARTD1.VOLUNIT IS NOT NULL 
		GROUP BY {cat_col}
		) TOT_YR
				
			LEFT JOIN (
				SELECT -- 365 ON TIME ORDERS
					CARTD1.{cat_col}, 
					count(PRCHS_DCMNT_ITEM) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_YR
				FROM 
                
				WHERE 
					PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -365 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -1 DAY)
					AND DIM_MTRL.MTRL_TYP = 'ZREV'
					AND PRCHS_STUS_ITEM BETWEEN '40' AND '60' 
					AND PSTNG_DT <= DATE_ADD(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), INTERVAL +5 DAY)
					AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
					AND LT_TRAN IS NOT NULL 
					AND VLR_MIN_ORD IS NOT NULL 
					AND CARTD1.{cat_col} IS NOT NULL 
					AND CARTD1.VOLUNIT IS NOT NULL
				GROUP BY {cat_col}) ON_TIME_YR 
					ON TOT_YR.{cat_col} = ON_TIME_YR.{cat_col}
			LEFT JOIN (
				SELECT -- LAST MONTH ALL ORDERS
					CARTD1.{cat_col}, 
					count(PRCHS_DCMNT_ITEM) TOT_ORD_PRCHS_QTY_LAST_MTH
				FROM 
                
				WHERE 
					PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -30 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -1 DAY)
					AND DIM_MTRL.MTRL_TYP = 'ZREV' 
					AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
					AND LT_TRAN IS NOT NULL 
					AND VLR_MIN_ORD IS NOT NULL
					AND CARTD1.{cat_col} IS NOT NULL 
					AND CARTD1.VOLUNIT IS NOT NULL 
				GROUP BY {cat_col}) TOT_LAST_MTH
					ON TOT_YR.{cat_col} = TOT_LAST_MTH.{cat_col}			
			LEFT JOIN (
				SELECT -- LAST MONTH ON TIME ORDERS
					CARTD1.{cat_col}, 
					count(PRCHS_DCMNT_ITEM) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_MTH
				FROM 
                
				WHERE 
					PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -30 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -1 DAY)
					AND DIM_MTRL.MTRL_TYP = 'ZREV'
					AND PRCHS_STUS_ITEM BETWEEN '40' AND '60' 
					AND PSTNG_DT <= DATE_ADD(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), INTERVAL +5 DAY)
					AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
					AND LT_TRAN IS NOT NULL 
					AND VLR_MIN_ORD IS NOT NULL 
					AND CARTD1.{cat_col} IS NOT NULL 
					AND CARTD1.VOLUNIT IS NOT NULL 
				GROUP BY {cat_col}) ON_TIME_LAST_MTH
					ON TOT_YR.{cat_col} = ON_TIME_LAST_MTH.{cat_col}  
		
			LEFT JOIN (
				SELECT -- LAST 2 MONTHS ALL ORDERS
					CARTD1.{cat_col}, 
					count(PRCHS_DCMNT_ITEM) TOT_ORD_PRCHS_QTY_LAST_TWO_MTH
				FROM 
                
				WHERE 
					PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -60 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -31 DAY)
					AND DIM_MTRL.MTRL_TYP = 'ZREV' 
					AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
					AND LT_TRAN IS NOT NULL 
					AND VLR_MIN_ORD IS NOT NULL
					AND CARTD1.{cat_col} IS NOT NULL 
					AND CARTD1.VOLUNIT IS NOT NULL 
				GROUP BY {cat_col}) TOT_LAST_TWO_MTH
					ON TOT_YR.{cat_col} = TOT_LAST_TWO_MTH.{cat_col}			
			LEFT JOIN (
				SELECT -- LAST 2 MONTHS ON TIME ORDERS
					CARTD1.{cat_col}, 
					count(PRCHS_DCMNT_ITEM) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_TWO_MTH
				FROM 
                
				WHERE 
					PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -60 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -31 DAY)
					AND DIM_MTRL.MTRL_TYP = 'ZREV'
					AND PRCHS_STUS_ITEM BETWEEN '40' AND '60' 
					AND PSTNG_DT <= DATE_ADD(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), INTERVAL +5 DAY)
					AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
					AND LT_TRAN IS NOT NULL 
					AND VLR_MIN_ORD IS NOT NULL 
					AND CARTD1.{cat_col} IS NOT NULL 
					AND CARTD1.VOLUNIT IS NOT NULL 
				GROUP BY {cat_col}) ON_TIME_LAST_TWO_MTH 
					ON TOT_YR.{cat_col} = ON_TIME_LAST_TWO_MTH.{cat_col}  
			LEFT JOIN (
				SELECT -- LAST 3 MONTHS ALL ORDERS
					CARTD1.{cat_col}, 
					count(PRCHS_DCMNT_ITEM) TOT_ORD_PRCHS_QTY_LAST_THREE_MTH
				FROM 
                
				WHERE 
					PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -90 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -61 DAY)
					AND DIM_MTRL.MTRL_TYP = 'ZREV' 
					AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
					AND LT_TRAN IS NOT NULL 
					AND VLR_MIN_ORD IS NOT NULL
					AND CARTD1.{cat_col} IS NOT NULL 
					AND CARTD1.VOLUNIT IS NOT NULL 
				GROUP BY {cat_col}) TOT_LAST_THREE_MTH 	
					ON TOT_YR.{cat_col} = TOT_LAST_THREE_MTH.{cat_col}			
			LEFT JOIN (
				SELECT -- LAST 3 MONTHS ON TIME ORDERS
					CARTD1.{cat_col}, 
					count(PRCHS_DCMNT_ITEM) TOT_ON_TIME_ORD_PRCHS_QTY_LAST_THREE_MTH
				FROM 
                
				WHERE 
					PRCHS_DCMNT_DT BETWEEN DATE_ADD(CURRENT_DATE(), INTERVAL -90 DAY) AND DATE_ADD(CURRENT_DATE(), INTERVAL -61 DAY)
					AND DIM_MTRL.MTRL_TYP = 'ZREV'
					AND PRCHS_STUS_ITEM BETWEEN '40' AND '60' 
					AND PSTNG_DT <= DATE_ADD(CAST(SCHDL_PLAN_DVSN_DCMNT_DT AS DATE), INTERVAL +5 DAY)
					AND SCHDL_PLAN_DVSN_DCMNT_DT IS NOT NULL 
					AND LT_TRAN IS NOT NULL 
					AND VLR_MIN_ORD IS NOT NULL 
					AND CARTD1.{cat_col} IS NOT NULL 
					AND CARTD1.VOLUNIT IS NOT NULL 
				GROUP BY {cat_col}) ON_TIME_LAST_THREE_MTH
					ON TOT_YR.{cat_col} = ON_TIME_LAST_THREE_MTH.{cat_col}  
)
ORDER BY 
    {cat_col}
"""

lst_group_cols = ['VEND_NR', 'DSTRBTN_CHNL','PRCHS_DCMNT_TYP','HIERCY_NODE_2','VOLUNIT']
lst_cat_cols = ['DSTRBTN_CHNL','PRCHS_DCMNT_TYP','HIERCY_NODE_2','VOLUNIT', 'SCHDL_PLAN_DVSN_DCMNT_DT', 'PRCHS_DCMNT_DT']
lst_num_cols = [
    'VOLUNIT_ITEM', 'QTY', 'GRS_VAL_SLS_CRNCY', 'VLR_MIN_ORD', 'GRS_WGT', 'LT_TRAN',
    'PROMISED_LEAD_TIME', 'DAYS_OPEN', 'TIME_SPNT_PRCNTG', 'TOT_ORD_PRCHS_QTY', 
    'TOT_ON_TIME_ORD_PRCHS_QTY', 'TOT_LATE_DEV_ORD_PRCHS_QTY', 'TOT_CANC_ORD_PRCHS_QTY']


schema_canc = [
    {'name':"CALC_DT", 'type':'DATE', 'mode':'NULLABLE', 'description':'REFERENCE DATE'},
    {'name':"PRCHS_NR", 'type':'INTEGER', 'mode':'NULLABLE', 'description':'PURCHASE DOCUMENT NUMBER'},
    {'name':"PRCHS_DCMNT_ITEM", 'type':'INTEGER', 'mode':'NULLABLE', 'description':'PURCHASE DOCUMENT ITEM NUMBER'},
    {'name':"CANC_PROBLTY", 'type':'FLOAT', 'mode':'NULLABLE', 'description':'CANCELATION PROBABILITY'},
    {'name':"TEC_CRE_DT", 'type':'DATETIME', 'mode':'NULLABLE', 'description':'DATE OF ROW CREATION'},
    {'name':"TEC_UPT_DT", 'type':'DATETIME', 'mode':'NULLABLE', 'description':'DATE OF ROW UPDATE'},
    {'name':"TEC_USER_UPT", 'type':'STRING', 'mode':'NULLABLE', 'description':'USER OR PROCESS'},
]

schema_late = [
    {'name':"CALC_DT", 'type':'DATE', 'mode':'NULLABLE', 'description':'REFERENCE DATE'},
    {'name':"PRCHS_NR", 'type':'INTEGER', 'mode':'NULLABLE', 'description':'PURCHASE DOCUMENT NUMBER'},
    {'name':"PRCHS_DCMNT_ITEM", 'type':'INTEGER', 'mode':'NULLABLE', 'description':'PURCHASE DOCUMENT ITEM NUMBER'},
    {'name':"LATE_PROBLTY", 'type':'FLOAT', 'mode':'NULLABLE', 'description':'LATE PROBABILITY'},
    {'name':"TEC_CRE_DT", 'type':'DATETIME', 'mode':'NULLABLE', 'description':'DATE OF ROW CREATION'},
    {'name':"TEC_UPT_DT", 'type':'DATETIME', 'mode':'NULLABLE', 'description':'DATE OF ROW UPDATE'},
    {'name':"TEC_USER_UPT", 'type':'STRING', 'mode':'NULLABLE', 'description':'USER OR PROCESS'},
]
